support oracle number(p,s) type
IvorySQL/IvorySQL pull request #35
Opened 2022-01-04 09:29 UTC by BingAo-Office

2022-01-11 10:59 UTC, rasifr requested changes
I think there are some issue still. After applying the patch, I have observed the following.

1. see below query, It should be able to execute without issues.

> postgres=# select 1/2::numeric;
ERROR:  operator is only a shell: integer / numeric
LINE 1: select 1/2::numeric;
                ^
postgres=# 

2. even after setting the compatibility mode, the error is still there. 

> postgres=# set compatible_mode TO oracle ;
SET
postgres=# select 1/2::numeric;
ERROR:  operator is only a shell: integer / numeric
LINE 1: select 1/2::numeric;
                ^
postgres=# 

3. and replacing numeric with number results in ambiguous operator selection.

> postgres=# select 1/2::number;
ERROR:  operator is not unique: integer / "number"
LINE 1: select 1/2::number;
                ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
postgres=#

2022-01-12 11:12 UTC, BingAo-Office commented
Thanks for your review ,  I found many errors and redundant operators through the inspection, which led to the above patch errors, which have been repaired now

2022-01-12 11:35 UTC, BingAo-Office commented on contrib/orafce/orafce--3.18.sql
> -/* oracle.number type support */
All of these can be implicitly converted to numeric implementations

2022-01-12 11:36 UTC, BingAo-Office commented on contrib/orafce/orafce--3.18.sql
> --- end
All of these can be implicitly converted to numeric implementations

2022-01-12 11:37 UTC, BingAo-Office commented on contrib/orafce/orafce--3.18.sql
> -
Adjust the position

2022-01-12 15:20 UTC, rasifr commented
@BingAo-Office Thanks for the update but it needs to be rebased again.

2022-01-14 11:10 UTC, rasifr approved these changes
everything seems to be working

2022-01-14 11:10 UTC, merged